version: "3"
services:
       rest-app:
           container_name: rest-app
           image: reinnatan/rest-app
           restart: always
           env_file: .env
           build: .
           ports:
             - "3030:3030"
           links:
             - mongo
           networks:
             - app-network
       mongo:
             container_name: mongo
             image: mongo
             networks:
               - app-network
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'

networks:
  app-network:
    driver: bridge